### PR TITLE
Remove a bunch of pointers

### PR DESCRIPTION
**Pull request by jrood-nrel**
I can't take all the pointer dereferencing anymore.

### CODE REVIEW

**Comment by esclapez** [comment]
That'll remove the native compatibility with a Chemkin-based code, but it might actually be already out the window, so that's probably fine.

**Comment by marchdf** [comment]
Do we know of any chemkin-based codes that are hooking into pelephysics and using our API?

**Comment by esclapez** [comment]
I don't know any ... I'm just mentioning it because that was the rational behind Fuego at the beginning, but now that we've moved away from it, it seems natural to go more modern/efficient implementation.

**Comment by jrood-nrel** [comment]
If anybody has any objections, I will be fine not making the changes. These changes just felt like a natural progression. I have some ideas I'm exploring in making this stuff faster on the GPU, but those don't really need this.

**Comment by marchdf** [comment]
I like this PR ;)

**Comment by jrood-nrel** [comment]
Alright let's decide if we want to do this or not.

**Review by hsitaram — APPROVED** [review]
all good! Its high time we remove these remnants from the C -> fortran -> C++ builds from back in the day.

**Review by baperry2 — APPROVED** [review]
I like having all the consts where appropriate in the EOS functions to make it crystal clear what is an input/output.

Having directly chemkin compatible interfaces is cool in principal but if no one is actually using the capability there's no point in making the code worse to keep it around.

**Review by marchdf — APPROVED** [review]

**Review by malihass — COMMENTED** [review]
This looks good to me. I ran a 0D reactor and compared successfully to Cantera for `dodecane_lu` and `dodecane_lu_qss`. Can we try to update the qss mechs as well?

**Review by malihass — APPROVED** [review]

**Review by esclapez — APPROVED** [review]

**Pull request merged**
