### PR TITLE
Add safegard on constant transport actual_transport otherwise blocking

### PR DESCRIPTION
**Pull request by esclapez**
when using fpe_trap_overflow.

### CODE REVIEW

**Comment by drummerdoc** [comment]
Not a huge fan of checking for nan's that way, but if it works, I'm good.

**Comment by esclapez** [comment]
Not even checking for nan, just checking that the coeff%mu(:), coeff%xi(:), ... are allocated.

**Comment by drummerdoc** [comment]
oh!  Is that the correct way to check?  Do we need to?  Can we declare it with a def known at compile time and have it always ok?

**Comment by esclapez** [comment]
We can't really do that, it is allocated/deallocated at various time depending on the transport properties you want to compute and the size depends on the size of the box and so on. Just commited a slight change, that is probably more straightforward.

**Comment by drummerdoc** [comment]
Again, didn't know that F90 would understand that code, which looks like you're checking a pointer.

**Comment by drummerdoc** [comment]
Oh...forgot to comment here that I was confused, and that what you did is fine.

**Review by drummerdoc — COMMENTED** [review]
Looks good to me

**Comment by EnnaDelfen** [comment]
I'm closing this since Emmanuel's commit in dev branch today took care of this !

**Pull request closed without merging**
