### PR TITLE
Fully GPU enabled set_sundials_solver_tols

### PR DESCRIPTION
**Pull request by cbauinge**
The SYCL computations in set_sundials_solver_tols were still performed on the CPU, resulting in a big bottleneck. I implemented them on the GPU.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
@cbauinge Thanks for this. We just require `clang-format -i` to be run on the source files for it to get merged.

**Comment by cbauinge** [comment]
> @cbauinge Thanks for this. We just require `clang-format -i` to be run on the source files for it to get merged.

Hi. Sorry about that. I did it now. Please let me know if there is something missing.

**Comment by jrood-nrel** [comment]
It looks like this doesn't work on the CPU. Instead, would we be able to change:
```
#if defined(AMREX_USE_HIP) || defined(AMREX_USE_CUDA)
```
to
```
#if defined(AMREX_USE_GPU)
```
and expect this to work with SyCL as well?

**Comment by jrood-nrel** [comment]
Or we could just have an extra block with this code with:
```
#elif defined(AMREX_USE_SYCL)
```

**Comment by jrood-nrel** [comment]
I'm seeing errors when running this on Intel GPUs as well:
```
... Initializing reactions, using interval dt = 1.498288935e-08

[CVODE ERROR]  CVodeSVtolerances
  abstol has negative component(s) (illegal).

amrex::Abort::7::Problem in setSundialsSolverTols !!!
```
I made another PR to deal with SyCL separately https://github.com/AMReX-Combustion/PelePhysics/pull/406

**Comment by jrood-nrel** [comment]
Actually I think all these code blocks can be a 1D `ParallelFor`. I will try that.

**Comment by jrood-nrel** [comment]
I think https://github.com/AMReX-Combustion/PelePhysics/pull/406 solves all these code blocks and the performance is similar (on Intel GPUs so far). So I think I will close this and use that PR.

**Comment by cbauinge** [comment]
Sorry for the delayed response. Looks like you managed to solve it, thank you!

**Pull request closed without merging**
