### PR TITLE
Trying to avoid global memory reads

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by hsitaram** [comment]
wish the fkernelspec changes were made once we merge in the previous PR, or @marchdf you could do the same to cvode as well.

**Comment by marchdf** [comment]
This is just for Jon's branch to try out and play with. All that will be
updated before that branch goes to development.

**Comment by hsitaram** [comment]
ahh.. sorry, my bad. should have caught that when CI was not running

**Comment by marchdf** [comment]
Haha

**Pull request closed without merging**
