### PR TITLE
Runtime selection of reactor integrators

### PR DESCRIPTION
**Pull request by marchdf**
Things left to do:
- [x] Fix HIP CVODE stuff -> Jon and Marc
- [x] Check OpenMP build
- [x] Figure out why we can't compile with BL_NO_FORT=TRUE in debug mode -> Jon and Marc
- [x] Verify `CKINDX` for `Null` mechanism is correct -> Lucas
- [x] Remove all fortran
- [x] Merge in Cvode
- [x] Remove `USE_SUNDIALS_PP`
- [x] Ensure clang-format passes
- [x] Remove `reactor.H` and `reactor.cpp`
- [x] Consolidate the CI, we can do fewer builds
- [x] Perform comparison to ensure all is well

### CODE REVIEW

**Comment by marchdf** [comment]
The ReactEval test case is looking good!

temp

**Comment by marchdf** [comment]
Now with Cvode CPU (can't get a GPU node right now, but Lucas tells me that cvode GPU is fine):
temp

**Comment by marchdf** [comment]
This is close to being done. Jon and I want to clean up a couple more things but I think it is ready to be reviewed. Good luck?

**Comment by marchdf** [comment]
Now with Cvode GPU:
temp

**Comment by jrood-nrel** [comment]
@esclapez Can you build with `TINY_PROFILE=TRUE`? It appears the code is missing definitions like this https://github.com/AMReX-Combustion/PelePhysics/blob/b2d45f0f683da5e3b5f89440ab35bf0e0df69c04/Reactions/cvode/reactor_cvode_GPU.cpp#L237

**Comment by esclapez** [comment]
True ! I've got that fixed somewhere. I need to push it up.

**Comment by drummerdoc** [comment]
This might be the most intense PR yet.

**Comment by esclapez** [comment]
The `CKINDX` for `Null` mechanism looks good: 1 element, 1 species, 0 reactions.

**Review by jrood-nrel — APPROVED** [review]
💯

**Pull request merged**
