### PR TITLE
Simplify arkode fkernelspec a bit

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by hsitaram** [comment]
only some aesthetics? we have to move this function outside of arkode/cvode as there is a copy in cvode as well

**Review by hsitaram — APPROVED** [review]

**Review by jrood-nrel — APPROVED** [review]

**Comment by marchdf** [comment]
yeah just simplifications

**Comment by marchdf** [comment]
@hsitaram I did it for cvode as well. I think we can consolidate later because there's also a CPU version in CVODE.

**Comment by jrood-nrel** [comment]
@hsitaram @esclapez Is this going to mess with anything you're working on? I think we should merge this before it gets out of date.

**Comment by esclapez** [comment]
Yes, I merging now is a good idea.

**Pull request merged**
