### PR TITLE
Fix error of PmfData on GPU

### LINKED ISSUE #454: Error in running PmfData::deallocate() on GPU
I was trying to use the `PmfData` class in my project. When running on GPU, an error occurred during `deallocate()`, saying that `CArena::free: unknown pointer !!!`.

Upon looking into the code, it seems that the error is caused by the fact that `m_data_d` is allocated with `The_Arena()` (line 48: `PMFData.H`) but is freed by `The_Device_Arena()` (line 61: `PMFData.H`). As a workaround, I substituted `The_Device_Arena()` with `The_Arena()`, so that the allocation and deallocation match. I have tested on both CPU and GPU, the issue appeared to be resolved.

I was wondering if this is a valid solution or if the line `The_Device_Arena()->free(m_data_d)` is intentional. I will be happy to contribute a pull request if the proposed solution aligns with the intended design.

Appreciate your insights. Thank you.

### PR DESCRIPTION
**Pull request by ensonun**
Closes #454

### CODE REVIEW

**Comment by marchdf** [comment]
Thank you for opening this! When I think about it, I wonder if we should be allocating use `the_device_arena` and then deallocating in the same arena. But maybe if you've tested on the GPU/CPU combo then it doesn't matter...

**Comment by marchdf** [comment]
We can ignore the failing CEPTR test, I fixed that in PR #452 .

**Comment by baperry2** [comment]
@ensonun Thank you for submitting this fix!

@marchdf I think this is fine as is unless @jrood-nrel objects. 

We use `The_Arena` for prob_parm but `The_Device_Arena` for trans_parm. These should be an alias of each other anyway except when running with `amrex.the_arena_is_managed = 1` (https://amrex-codes.github.io/amrex/docs_html/GPU.html?highlight=the_arena_is_managed#memory-allocation).

**Review by baperry2 — APPROVED** [review]

**Review by jrood-nrel — APPROVED** [review]

**Comment by jrood-nrel** [comment]
Thanks for this @ensonun . Maybe this is why the PMF files here never worked for us in PeleC?

**Comment by ensonun** [comment]
Thanks all for approving this. It’s my pleasure being able to help!

**Comment by marchdf** [comment]
@ensonun I think I created some conflicts with my latest commit (a bunch of file reorgs). Can you fix the conflict? Thank you!

**Pull request closed without merging**
