### PR TITLE
Updated SootReaction

### PR DESCRIPTION
**Pull request by ldowen**
Just updated the soot reaction.

### CODE REVIEW

**Review by jrood-nrel — APPROVED** [review]

**Comment by jrood-nrel** [comment]
Actually I have a question. Is it necessary to use `DeviceVector`? It seems like `GpuArray` might suffice since it doesn't need to be a dynamic size.

**Comment by ldowen** [comment]
I just updated the mechanism using the pickler and changed the names of the files. I didn't change anything else. Did I do something wrong?

**Comment by jrood-nrel** [comment]
Oh, I guess I don't know where the `DeviceVector` came from then. @marchdf do you know?

**Comment by ldowen** [comment]
It seems like all of the mechanisms use that.

**Comment by esclapez** [comment]
I think it is coming from a WIP to allow Analytical Jacobian with HIP, so I'm not sure PeleC is using any of it. You can probably open an issue about it to remember that this need further work.

**Review by marchdf — APPROVED** [review]

**Comment by marchdf** [comment]
I don't know about this Device Vector stuff... sounds like @esclapez has the right idea though.

**Pull request merged**
