### PR TITLE
Upgrade CEPTR thermo generation

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Review by baperry2 — APPROVED** [review]

**Comment by baperry2** [comment]
thoughts on not updating all the mechanisms until you finish this process?

**Comment by marchdf** [comment]
some of this actually fixes warnings that are triggered in PeleC so I think we should keep these updates.

**Comment by jrood-nrel** [comment]
Do we want all these 0 terms being generated?

**Comment by marchdf** [comment]
Oh nice catch. I can fix that.

**Comment by marchdf** [comment]
Fixed those useless zeros ;)

**Review by jrood-nrel — APPROVED** [review]

**Comment by malihass** [comment]
This looks good to me, I also like that the midpoint are ordered now!

**Review by malihass — APPROVED** [review]

**Comment by marchdf** [comment]
Yes I fixed that arbitrary midpoint ordering ;)

**Pull request merged**
