### PR TITLE
Fixed bug where CPickler did not make the k_r double

### PR DESCRIPTION
**Pull request by ldowen**

### CODE REVIEW

**Review by drummerdoc — APPROVED** [review]
Odd, how does it even compile without that fix?

**Comment by EnnaDelfen** [comment]
He must be doing something very specific, usually k_r does not appear in tha CPickler generated function. But yes, when we need it we need it declared !

**Comment by EnnaDelfen** [comment]
I am actually curious to know for which situation it lead to an error ? Do you specifi reverses directly somewhere in one of your application ?

**Review by EnnaDelfen — APPROVED** [review]

**Comment by ldowen** [comment]
That is correct. I have an application where the mechanism requires specified reverse reaction rates that I tried running on GPUs.

**Pull request merged**
