### PR TITLE
Update to SUNDIALS 6

### PR DESCRIPTION
**Pull request by balos1**
Needs https://github.com/AMReX-Codes/amrex/pull/2551. @jrood-nrel @esclapez @gardner48

### CODE REVIEW

**Comment by esclapez** [comment]
@balos1 Hi Cody. Currently, some clang formatting issues are blocking this PR. Can you address those ? Alternatively I can do it if you give me the right to push to your branch. Thanks !

**Comment by jrood-nrel** [comment]
I just verified the CI checked out the `1404c4a` version of AMReX. I'm not sure why that header isn't being found but I haven't looked very hard. @balos1 Do you want any help solving this or do you have an idea what's going wrong?

**Comment by gardner48** [comment]
@jrood-nrel I ran into this issue with PeleLMeX and the problem was `amrex/Src/Extern/SUNDIALS` not getting included. Adding `USE_SUNDIALS=TRUE` to the Makefile fixed the issue for me.

**Comment by esclapez** [comment]
We'll always need SUNDIALS now, so we can probably add this to `Testing/Exec/Make.PelePhysics` and the equivalent in C and LM. But maybe this also triggers other things.

**Comment by jrood-nrel** [comment]
Yeah I think we kind of do all the sundials stuff manually. Maybe https://github.com/AMReX-Combustion/PelePhysics/blob/development/ThirdParty/Make.ThirdParty could be less complicated, as well as https://github.com/AMReX-Combustion/PelePhysics/blob/development/Reactions/Make.package

**Comment by jrood-nrel** [comment]
It looks like `Make.ThirdParty` does get simplified here. It looks like transport doesn't have `USE_SUNDIALS` but the other tests do.

**Comment by balos1** [comment]
> We'll always need SUNDIALS now, so we can probably add this to `Testing/Exec/Make.PelePhysics` and the equivalent in C and LM. But maybe this also triggers other things.

Yes, this is what needs to be done and what I did in PeleC.

**Comment by balos1** [comment]
@esclapez Looks like all the checks are passing now.

**Comment by esclapez** [comment]
Awesome. I'll give a try to LM on both CPU/GPU with this version and it should be good to go on my side.

**Comment by esclapez** [comment]
All good on LM/LMeX side.

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
