### PR TITLE
Update SUNDIALS to 7.0

### PR DESCRIPTION
**Pull request by jrood-nrel**
Somebody was trying SUNDIALS 7.0 with PeleLMeX and these are what I think are the necessary changes if you want them.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
Looks like there is more to it than this.

**Review by baperry2 — APPROVED** [review]
Looks good to me, although at some point we'll have to go back and handle all the deprecated stuff.

**Comment by jrood-nrel** [comment]
I can add that to this PR.

**Comment by marchdf** [comment]
@hsitaram can you make sure the changes in `Source/Reactions/ReactorArkode.cpp` make sense? Is there an easy way to test?

**Comment by jrood-nrel** [comment]
@balos1 Do these changes look right to remove the deprecation warnings?

**Comment by balos1** [comment]
> @balos1 Do these changes look right to remove the deprecation warnings?

Yep, this looks good!

**Pull request merged**
