### PR TITLE
Lucas/fix reaction order fuego

### PR DESCRIPTION
**Pull request by esclapez**
Implementing AF changes in Fuego for reaction order of global mechanisms and update of the chem-CH4-2S and JL4.

### CODE REVIEW

**Comment by EnnaDelfen** [comment]
Seems fine. We will have to implement the changes linked to the orders in the Jac too at some point. It's a partial fix for now.

**Comment by esclapez** [comment]
Yes, indeed ! We don't really need the analytical Jacobian of 2-steps schemes right now. But at least we are able to run the new regtests with the master branch of PelePhysics, which seems less confusing (and easier for me to handle in the regression testing *.ini files). We can let the branch open as a reminder ...

**Comment by drummerdoc** [comment]
Made an "Issue" for this topic to try to guard against it getting lost in the noise.

**Comment by EnnaDelfen** [comment]
I'm very proud of us for keeping that... But why wasn't this merged in dev though ?

**Comment by drummerdoc** [comment]
Probably because the person that made this PR chose `master` as the target.

**Pull request merged**
