### PR TITLE
Enable pythia with python 3

### PR DESCRIPTION
**Pull request by marchdf**
This PR is a large upgrade of pythia. It includes:
- the interchangeable use python2 or python3 for `pythia`
- `black` code formatting for python code
- `isort` import formatting for python code
- removal of `setup.sh` (unnecessary now, if you have a sane python env then all you need to do is `make-mechanism.sh`, python takes care of knowing the paths, etc)
- `pyproject.toml` to ensure cohesion in package expectations
- integration with `poetry` for fast python env creation
- CI for pythia (checks proper python code formatting and that `make-mechanism.sh` runs)
- All mechanisms were regenerated (no real changes noticed)
- a version bump of pythia because all good things need a version bump

Things I thought about doing and then discarded:
- building `pythia` from the ground up: total madness, the dependencies/object inheritance was sometimes 5 deep, impossible to figure out what was actually needed and what was not
- moving completely to python 3: I kept python 2 operability because (horrors) some people still use python 2
- inclusion of `flake8` linting: as mentioned above `pythia` is madness and there were _way_ too many linting errors for one person to deal with

I honestly don't know how to properly review this PR. Any suggestions are welcome. But here are some thoughts:
- focus on `mechanism.H`: you will see tiny diffs here that were actually due to other PRs (I think)
- try it out. Pull this branch, `cd` to a Model folder and `make-mechanism.sh`... Assuming you have a sane python environment... (quick and dirty way: `conda create -n python3 python=3.8 anaconda` for python3 and `conda create -n python2 python=2.7 anaconda` for python2)

The big thing to agree on is the use of code formatting (black and isort) for python code. That's probably the only thing that will have an impact on developers. This is like imposing `clang-format` for c++ code.

### CODE REVIEW

**Review by drummerdoc — APPROVED** [review]
Well, it seems to not fail. It also indeed gives small diffs from before.  It does require that you set the PELE_PHYSICS_HOME environment variable.  I dunno, I guess I'm in...

**Comment by marchdf** [comment]
@drummerdoc It should not require `PELE_PHYSICS_HOME` since it will default it to something sane. Did it give you an issue?

**Comment by drummerdoc** [comment]
> @drummerdoc It should not require `PELE_PHYSICS_HOME` since it will default it to something sane. Did it give you an issue?

Yes, it failed.  

../mechanism_builder.sh: line 4: realpath: command not found
Using PELE_PHYSICS_HOME: . Set PELE_PHYSICS_HOME you want a different one.
Using environment python: /usr/bin/python. Set FUEGO_PYTHON if you want a different one.
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Support/Fuego/Pythia/products/bin/fmc.py': [Errno 2] No such file or directory

**Comment by marchdf** [comment]
ah. you don't have `realpath`. Which means you don't have GNU `coreutils`. Which means that was a bad assumption on my part. I can fix that.

**Comment by marchdf** [comment]
@drummerdoc Ok I pushed a fix... works on my mac. Hopefully it works for you too now.

**Comment by drummerdoc** [comment]
> @drummerdoc Ok I pushed a fix... works on my mac. Hopefully it works for you too now.

Yep, looks good!

**Review by esclapez — APPROVED** [review]
Tested successfully on my MAC laptop and an Ubuntu desktop for a couple of mechanisms.
Looks good ! Thanks !

**Review by hsitaram — APPROVED** [review]

**Pull request merged**
