### PR TITLE
Vector->Array for typVals

### PR DESCRIPTION
**Pull request by drummerdoc**
This seems to fix the error dump at the end of the runs

### CODE REVIEW

**Comment by EnnaDelfen** [comment]
looks good to me, lucas can test it I'm sure

**Review by EnnaDelfen — APPROVED** [review]

**Comment by drummerdoc** [comment]
Hmmm, I see the error Lucas saw before when I try to run PeleLM:
```
[CVODE ERROR]  cvInitialSetup
  Initial ewt has component(s) equal to zero (illegal).
```
Don't approve yet.

**Comment by esclapez** [comment]
I see it too (on Ascent with the PeleProd setup)

**Comment by drummerdoc** [comment]
found/fixed issue.

**Comment by esclapez** [comment]
Seems to run smoothly.

**Review by esclapez — APPROVED** [review]

**Pull request merged**
