### PR TITLE
Better typical values output.

### PR DESCRIPTION
**Pull request by marchdf**

### CODE REVIEW

**Comment by esclapez** [comment]
You're printing before passing the `ExtTypVal` into the `m_typ_val` vector. Is that on purpose ?

**Comment by marchdf** [comment]
nope that's a mistake. thanks!

**Review by esclapez — APPROVED** [review]

**Comment by marchdf** [comment]
I am still not sure about this. Right now I have PeleC looking like:
```
...estimated hydro-limited timestep at level 0: 5.167702019e-08
PeleC::estTimeStep (hydro-limited) at level 0:  estdt = 5.167702019e-08
...estimated hydro-limited timestep at level 1: 2.587696453e-08
PeleC::estTimeStep (hydro-limited) at level 1:  estdt = 2.587696453e-08
PeleC::compute_new_dt : limiting dt at level 0
 ... new dt computed: 5.167702019e-08
 ... but limiting to: 5.684472226e-09 = 1.1 * 5.167702024e-09
PeleC::compute_new_dt : limiting dt at level 1
 ... new dt computed: 2.587696453e-08
 ... but limiting to: 2.842236113e-09 = 1.1 * 2.583851012e-09
[Level 0 step 2] ADVANCE with dt = 5.684472226e-09
SDC iteration 1 of 2.
... Computing diffusion terms at t^(n)
... Computing hydro advance
... Computing diffusion terms at t^(n+1,1)
... Computing reactions for dt = 5.684472226e-09
SDC iteration 2 of 2.
... Computing hydro advance
... Computing diffusion terms at t^(n+1,2)
... Computing reactions for dt = 5.684472226e-09
[Level 0 step 2] Advanced 8192 cells
[Level 1 step 3] ADVANCE with dt = 2.842236113e-09
SDC iteration 1 of 2.
... Computing diffusion terms at t^(n)
... Computing hydro advance
... Computing diffusion terms at t^(n+1,1)
... Computing reactions for dt = 2.842236113e-09
SDC iteration 2 of 2.
... Computing hydro advance
... Computing diffusion terms at t^(n+1,2)
... Computing reactions for dt = 2.842236113e-09
[Level 1 step 3] Advanced 4096 cells
Setting typical values for level 1
Set the typical values for PelePhysics ODE integration:
H2 : 5.843589412e-06
O2 : 0.0001348601753
H2O : 1.214039023e-05
H : 6.116770364e-09
O : 1.171797621e-07
OH : 1.63336712e-07
HO2 : 7.631787541e-08
H2O2 : 2.930780902e-08
N2 : 0.0004793723297
Temp : 859.5752289
[Level 1 step 4] ADVANCE with dt = 2.842236113e-09
SDC iteration 1 of 2.
... Computing diffusion terms at t^(n)
... Computing hydro advance
... Computing diffusion terms at t^(n+1,1)
... Computing reactions for dt = 2.842236113e-09
SDC iteration 2 of 2.
... Computing hydro advance
... Computing diffusion terms at t^(n+1,2)
... Computing reactions for dt = 2.842236113e-09
[Level 1 step 4] Advanced 4096 cells
Setting typical values for level 1
Set the typical values for PelePhysics ODE integration:
H2 : 5.843588797e-06
O2 : 0.0001348601752
H2O : 1.214038223e-05
H : 6.119798208e-09
O : 1.171847308e-07
OH : 1.63313414e-07
HO2 : 7.627612834e-08
H2O2 : 2.930810754e-08
N2 : 0.0004793723304
Temp : 859.575134
```

Kinda ugly... Should we write these to file maybe instead? Just feels kinda randomly in there. Do we only print on `verbose` maybe? Do we need to know these all the time?

**Comment by marchdf** [comment]
In PeleC, `set_typical_values` is called in `post_init`, `post_restart`, `post_regrid`, and `post_timestep`. Maybe all those are necessary?

**Comment by hsitaram** [comment]
Post init and restart are absolutely necessary. Post regrid is necessary
when say a fine level suddenly is created at a flame. Post timestep could
be lagged a bit just with an interval

**Comment by marchdf** [comment]
Excellent, thanks for the explanation, Hari! I decided to use the `ode.verbose` flag to control that output.

**Review by jrood-nrel — APPROVED** [review]

**Pull request merged**
