### PR TITLE
Reduce register and memory usage in productionRate function

### PR DESCRIPTION
**Pull request by jrood-nrel**

### CODE REVIEW

**Review by drummerdoc — COMMENTED** [review]
can we get rid of the divide by refCinv too?

**Review by drummerdoc — COMMENTED** [review]
rmap is definitely needed in post-processing to understand chemistry reactions.  You can remove it here but we need a way to generate it in post processing if necessary.

**Comment by jrood-nrel** [comment]
fcompare from PeleC PMF:
```
% ~/combustion/plot_tools/fcompare.llvm.ex old/plt00000 new/plt00000
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 xmom                                             0                         0
 ymom                                             0                         0
 zmom                                             0                         0
 rho_E                                            0                         0
 rho_e                                            0                         0
 Temp                                             0                         0
 rho_H2                                           0                         0
 rho_H                                            0                         0
 rho_O                                            0                         0
 rho_O2                                           0                         0
 rho_OH                                           0                         0
 rho_H2O                                          0                         0
 rho_HO2                                          0                         0
 rho_CH2                                          0                         0
 rho_CH2(S)                                       0                         0
 rho_CH3                                          0                         0
 rho_CH4                                          0                         0
 rho_CO                                           0                         0
 rho_CO2                                          0                         0
 rho_HCO                                          0                         0
 rho_CH2O                                         0                         0
 rho_CH3O                                         0                         0
 rho_C2H4                                         0                         0
 rho_C2H5                                         0                         0
 rho_C2H6                                         0                         0
 rho_N2                                           0                         0
 rho_AR                                           0                         0
 rho_omega_H2                       6.205905473e-16           6.814022181e-12
 rho_omega_H                        2.327172201e-16           4.111281207e-12
 rho_omega_O                        1.241167542e-15           4.947241836e-12
 rho_omega_O2                       1.270959032e-12           7.906741124e-10
 rho_omega_OH                       4.964697273e-15           1.814520068e-11
 rho_omega_H2O                      1.588698791e-13            1.08615642e-10
 rho_omega_HO2                      3.636259503e-18           8.033738538e-13
 rho_omega_CH2                      1.517883041e-18           1.003915987e-14
 rho_omega_CH2(S)                   5.854691731e-18           9.933577663e-15
 rho_omega_CH3                      3.252606517e-18           1.007216528e-14
 rho_omega_CH4                      3.177397581e-13           1.844255205e-09
 rho_omega_CO                       1.985873488e-14           1.394447204e-11
 rho_omega_CO2                      7.943493953e-14           3.550012981e-11
 rho_omega_HCO                      1.231010188e-19           2.861963963e-14
 rho_omega_CH2O                     7.398096604e-23           5.622187385e-12
 rho_omega_CH3O                     4.543838814e-28           4.929116853e-14
 rho_omega_C2H4                     4.623721689e-24           1.736986504e-12
 rho_omega_C2H5                     4.304453426e-32           7.410040878e-14
 rho_omega_C2H6                     2.311860844e-24           1.146231023e-12
 rho_omega_N2                        2.54191788e-12                         1
 rho_omega_AR                       3.163678761e-72                         1
 rhoe_dot                                         0                         0
 heatRelease                          0.01483397186           2.859874109e-11
 level = 1
 density                                          0                         0
 xmom                                             0                         0
 ymom                                             0                         0
 zmom                                             0                         0
 rho_E                                            0                         0
 rho_e                                            0                         0
 Temp                                             0                         0
 rho_H2                                           0                         0
 rho_H                                            0                         0
 rho_O                                            0                         0
 rho_O2                                           0                         0
 rho_OH                                           0                         0
 rho_H2O                                          0                         0
 rho_HO2                                          0                         0
 rho_CH2                                          0                         0
 rho_CH2(S)                                       0                         0
 rho_CH3                                          0                         0
 rho_CH4                                          0                         0
 rho_CO                                           0                         0
 rho_CO2                                          0                         0
 rho_HCO                                          0                         0
 rho_CH2O                                         0                         0
 rho_CH3O                                         0                         0
 rho_C2H4                                         0                         0
 rho_C2H5                                         0                         0
 rho_C2H6                                         0                         0
 rho_N2                                           0                         0
 rho_AR                                           0                         0
 rho_omega_H2                       2.234106997e-14           2.409467861e-12
 rho_omega_H                        4.022129851e-14           9.865262331e-12
 rho_omega_O                        9.929557176e-15           6.705758538e-13
 rho_omega_O2                       5.083835761e-12           1.229319776e-11
 rho_omega_OH                       1.054684118e-12           3.833152421e-11
 rho_omega_H2O                      6.354777815e-13           2.290353203e-12
 rho_omega_HO2                      6.516271897e-15           5.404704608e-12
 rho_omega_CH2                      1.679580466e-12           1.136620039e-09
 rho_omega_CH2(S)                   2.989826014e-12            3.61394218e-08
 rho_omega_CH3                      9.184664748e-13           3.572474732e-11
 rho_omega_CH4                       1.27095894e-12           8.205251737e-12
 rho_omega_CO                       1.270962502e-12           6.144838853e-12
 rho_omega_CO2                      6.354795162e-13           4.055216311e-12
 rho_omega_HCO                      1.334646369e-13           1.552159502e-10
 rho_omega_CH2O                      5.70940864e-14           5.980338126e-12
 rho_omega_CH3O                     4.654479926e-16           1.152302682e-12
 rho_omega_C2H4                     7.447167882e-15           4.877822071e-13
 rho_omega_C2H5                     1.086045316e-15           1.333111936e-12
 rho_omega_C2H6                     7.447167882e-15           4.953445099e-13
 rho_omega_N2                       1.016767152e-11                         2
 rho_omega_AR                       1.012377203e-70                         2
 rhoe_dot                                         0                         0
 heatRelease                           0.2327613831           4.889761601e-12
```

**Comment by jrood-nrel** [comment]
```
% ~/combustion/plot_tools/fcompare.llvm.ex old/plt00002 new/plt00002
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                            1.734723476e-18           1.545388652e-15
 xmom                               1.978809911e-14           1.167885731e-10
 ymom                               2.745515675e-14            1.59101213e-10
 zmom                               3.603367604e-14           8.006082855e-13
 rho_E                              3.259629011e-09           8.420512468e-16
 rho_e                              3.259629011e-09           8.420510544e-16
 Temp                                5.78666004e-11           2.644573401e-14
 rho_H2                             1.000557669e-20           2.453156343e-14
 rho_H                              7.506972071e-20           1.854660844e-12
 rho_O                              2.117582368e-22           6.863782243e-16
 rho_O2                             2.981555974e-18           1.206518233e-14
 rho_OH                             1.203219782e-18           1.487239369e-12
 rho_H2O                            4.821735052e-19             2.5248597e-14
 rho_HO2                             1.53127675e-20           2.838105243e-13
 rho_CH2                            8.460388183e-19           1.885967002e-10
 rho_CH2(S)                         2.959522778e-18           8.764289722e-09
 rho_CH3                            1.482897618e-18           9.995905311e-12
 rho_CH4                            7.115076757e-19           1.148544447e-14
 rho_CO                             2.756192271e-18           3.399476962e-13
 rho_CO2                              1.6093626e-20           8.041168093e-16
 rho_HCO                            5.618707029e-20           8.561560739e-12
 rho_CH2O                            1.05085025e-20           4.361559046e-14
 rho_CH3O                           8.106370003e-23           8.218016837e-15
 rho_C2H4                           1.588186776e-22           6.501109796e-16
 rho_C2H5                           1.220091404e-22           1.911960897e-14
 rho_C2H6                           1.852884572e-22           6.651614508e-16
 rho_N2                             1.084202172e-18           1.332849749e-15
 rho_AR                             2.698802673e-78           4.816307347e-16
 rho_omega_H2                       6.843223904e-13           1.498869562e-10
 rho_omega_H                        4.288509191e-12           2.016921631e-09
 rho_omega_O                        4.054048763e-15           5.260761009e-13
 rho_omega_O2                       1.783576403e-10           7.402980317e-10
 rho_omega_OH                       6.873210074e-11            4.47874414e-09
 rho_omega_H2O                      2.727713845e-11           1.888650913e-10
 rho_omega_HO2                       8.74274462e-13           8.339693539e-10
 rho_omega_CH2                      5.169935075e-11           1.177952882e-08
 rho_omega_CH2(S)                   1.690644066e-10           2.196627164e-08
 rho_omega_CH3                      8.467765898e-11           7.307990513e-09
 rho_omega_CH4                      4.152114416e-11           5.282696562e-10
 rho_omega_CO                       1.573588803e-10           1.495649222e-09
 rho_omega_CO2                      1.257827176e-12           1.095481063e-11
 rho_omega_HCO                      4.568350797e-12           8.505137369e-09
 rho_omega_CH2O                     8.613209972e-13           1.663410402e-10
 rho_omega_CH3O                     6.624285539e-15           3.220270594e-11
 rho_omega_C2H4                     3.895755246e-15           5.096903629e-13
 rho_omega_C2H5                     9.716240399e-15           1.838010944e-11
 rho_omega_C2H6                     1.122539561e-14           1.542530312e-12
 rho_omega_N2                       1.004542334e-11              0.7769507087
 rho_omega_AR                       4.429167035e-71               1.000003607
 rhoe_dot                             0.01091428823               1.223855597
 heatRelease                            27.08335364           1.048212301e-09
 level = 1
 density                            6.071532166e-18           5.409048761e-15
 xmom                               1.234841663e-13            2.97624519e-10
 ymom                               1.075422252e-13           2.638040525e-10
 zmom                               1.386252224e-13           3.053427683e-12
 rho_E                              1.443549991e-08           3.729193593e-15
 rho_e                              1.443549991e-08           3.729192741e-15
 Temp                                1.55523594e-10           7.566993791e-14
 rho_H2                             2.509335106e-20            5.40098205e-14
 rho_H                              1.918398472e-19             4.5851926e-12
 rho_O                              4.764560328e-22           1.485995024e-15
 rho_O2                             7.155734338e-18           2.895751608e-14
 rho_OH                             3.072456429e-18           3.766057026e-12
 rho_H2O                            1.236668103e-18           6.414434534e-14
 rho_HO2                             3.95723205e-20           5.464014969e-13
 rho_CH2                            2.152806743e-18           2.441146775e-10
 rho_CH2(S)                         7.556552614e-18           8.632075575e-09
 rho_CH3                            3.796785714e-18           1.373335613e-11
 rho_CH4                            1.694065895e-18           2.734737496e-14
 rho_CO                             7.044667143e-18           7.624468833e-13
 rho_CO2                            5.082197684e-20           2.656236132e-15
 rho_HCO                            1.496246685e-19           1.174962388e-11
 rho_CH2O                           2.811090594e-20           9.598708044e-14
 rho_CH3O                           2.415367389e-22            1.30200101e-14
 rho_C2H4                           7.940933881e-22           2.339139394e-15
 rho_C2H5                           2.895132144e-22            2.34466282e-14
 rho_C2H6                           1.111730743e-21           2.471633379e-15
 rho_N2                             4.553649124e-18            5.59817901e-15
 rho_AR                             4.318084278e-78           7.208680581e-16
 rho_omega_H2                        1.75779622e-12           1.921195515e-10
 rho_omega_H                         1.08031868e-11           2.770551929e-09
 rho_omega_O                        1.211791084e-14           8.180853295e-13
 rho_omega_O2                       4.453460101e-10           1.073328249e-09
 rho_omega_OH                       1.730075701e-10           6.172293757e-09
 rho_omega_H2O                      6.896897333e-11           2.496571933e-10
 rho_omega_HO2                      2.231464959e-12           1.752918827e-09
 rho_omega_CH2                      1.329966369e-10           7.874624971e-09
 rho_omega_CH2(S)                    4.25507761e-10           1.291298171e-08
 rho_omega_CH3                      2.137928081e-10             8.8248204e-09
 rho_omega_CH4                      1.048513984e-10           6.817293921e-10
 rho_omega_CO                       3.965253074e-10           1.911980828e-09
 rho_omega_CO2                      3.112943388e-12           1.986465204e-11
 rho_omega_HCO                      1.172122143e-11           8.014252081e-09
 rho_omega_CH2O                     2.144720165e-12           2.074444924e-10
 rho_omega_CH3O                     1.709125463e-14           4.310617326e-11
 rho_omega_C2H4                     1.232867974e-14           8.058856519e-13
 rho_omega_C2H5                     2.342596332e-14           3.051044525e-11
 rho_omega_C2H6                     2.792297643e-14           1.932011634e-12
 rho_omega_N2                       3.250835712e-11               1.459413215
 rho_omega_AR                       1.012393958e-70               1.999976107
 rhoe_dot                             0.02182471752                 1.9990798
 heatRelease                            68.25567198           1.437335648e-09
```

**Comment by jrood-nrel** [comment]
This is providing a 1.42x speedup for the PeleC drm19 PMF test case.

**Comment by jrood-nrel** [comment]
All relevant mechanisms regenerated and I ran a script to test compiling them all.

**Comment by jrood-nrel** [comment]
Diffs checked on GPU:
```
fcompare.gnu.haswell.ex old/plt00000 new/plt00000

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 xmom                                             0                         0
 ymom                                             0                         0
 zmom                                             0                         0
 rho_E                                            0                         0
 rho_e                                            0                         0
 Temp                                             0                         0
 rho_H2                                           0                         0
 rho_H                                            0                         0
 rho_O                                            0                         0
 rho_O2                                           0                         0
 rho_OH                                           0                         0
 rho_H2O                                          0                         0
 rho_HO2                                          0                         0
 rho_CH2                                          0                         0
 rho_CH2(S)                                       0                         0
 rho_CH3                                          0                         0
 rho_CH4                                          0                         0
 rho_CO                                           0                         0
 rho_CO2                                          0                         0
 rho_HCO                                          0                         0
 rho_CH2O                                         0                         0
 rho_CH3O                                         0                         0
 rho_C2H4                                         0                         0
 rho_C2H5                                         0                         0
 rho_C2H6                                         0                         0
 rho_N2                                           0                         0
 rho_AR                                           0                         0
 rho_omega_H2                       1.241181095e-15           1.362804215e-11
 rho_omega_H                        3.102986618e-16           5.481868557e-12
 rho_omega_O                        2.482335084e-15           9.894481681e-12
 rho_omega_O2                       2.541917882e-12           1.581348158e-09
 rho_omega_OH                       9.929340336e-15           3.629019245e-11
 rho_omega_H2O                      2.383048186e-13           1.629234526e-10
 rho_omega_HO2                      5.361162691e-18           1.038914862e-11
 rho_omega_CH2                      1.790509066e-16           2.598773549e-11
 rho_omega_CH2(S)                   6.979687011e-16           2.598982742e-11
 rho_omega_CH3                      3.824404579e-16           2.599083494e-11
 rho_omega_CH4                      6.354794705e-13           8.094978714e-08
 rho_omega_CO                       2.978823785e-14           2.091680174e-11
 rho_omega_CO2                      1.588698791e-13           7.100025889e-11
 rho_omega_HCO                      5.093738507e-18           2.590511668e-11
 rho_omega_CH2O                     1.109698335e-22           8.416291929e-12
 rho_omega_CH3O                     5.033721436e-26           5.595758886e-12
 rho_omega_C2H4                     1.470184292e-23           5.631742119e-12
 rho_omega_C2H5                     5.972730055e-31           1.350291221e-12
 rho_omega_C2H6                     1.184831214e-23           5.989159925e-12
 rho_omega_N2                                     0                         0
 rho_omega_AR                                     0                         0
 rhoe_dot                                         0                         0
 heatRelease                          0.02964908537           5.716112427e-11
 level = 1
 density                                          0                         0
 xmom                                             0                         0
 ymom                                             0                         0
 zmom                                             0                         0
 rho_E                                            0                         0
 rho_e                                            0                         0
 Temp                                             0                         0
 rho_H2                                           0                         0
 rho_H                                            0                         0
 rho_O                                            0                         0
 rho_O2                                           0                         0
 rho_OH                                           0                         0
 rho_H2O                                          0                         0
 rho_HO2                                          0                         0
 rho_CH2                                          0                         0
 rho_CH2(S)                                       0                         0
 rho_CH3                                          0                         0
 rho_CH4                                          0                         0
 rho_CO                                           0                         0
 rho_CO2                                          0                         0
 rho_HCO                                          0                         0
 rho_CH2O                                         0                         0
 rho_CH3O                                         0                         0
 rho_C2H4                                         0                         0
 rho_C2H5                                         0                         0
 rho_C2H6                                         0                         0
 rho_N2                                           0                         0
 rho_AR                                           0                         0
 rho_omega_H2                       7.447167882e-15           8.031731152e-13
 rho_omega_H                        1.241194647e-15            3.04432772e-13
 rho_omega_O                        9.929394546e-15           6.705647716e-13
 rho_omega_O2                       2.541918065e-12           6.146592168e-12
 rho_omega_OH                       4.468300729e-14           1.623955799e-12
 rho_omega_H2O                      4.766187445e-13           1.717809357e-12
 rho_omega_HO2                      1.861791971e-15           1.544203534e-12
 rho_omega_CH2                      7.059153609e-14           4.772582471e-11
 rho_omega_CH2(S)                   1.153319214e-13           1.385020678e-09
 rho_omega_CH3                      3.847660038e-14           1.496584124e-12
 rho_omega_CH4                      6.354794891e-13           4.102625403e-12
 rho_omega_CO                       2.383093722e-13           1.152171553e-12
 rho_omega_CO2                      4.766187445e-13           3.041470868e-12
 rho_omega_HCO                      4.072588621e-15           4.737012474e-12
 rho_omega_CH2O                     7.447167882e-15           7.800586165e-13
 rho_omega_CH3O                     4.654479926e-16           1.152301223e-12
 rho_omega_C2H4                     7.447167882e-15           4.877821998e-13
 rho_omega_C2H5                     4.654479926e-16           5.713329063e-13
 rho_omega_C2H6                     7.447167882e-15           4.953445139e-13
 rho_omega_N2                                     0                         0
 rho_omega_AR                                     0                         0
 rhoe_dot                                         0                         0
 heatRelease                          0.07733571529           1.624635459e-12


fcompare.gnu.haswell.ex old/plt00005 new/plt00005

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                            1.301042607e-18           1.159041489e-15
 xmom                               1.529164883e-14           1.725901659e-11
 ymom                               1.268944904e-14           1.368162238e-11
 zmom                               2.017136458e-14           4.387925778e-13
 rho_E                              1.862645149e-09            4.81172141e-16
 rho_e                              1.862645149e-09           4.811720311e-16
 Temp                               3.183231456e-12           1.454773169e-15
 rho_H2                             3.176373552e-22           7.788384699e-16
 rho_H                              2.867390998e-22           7.084167921e-15
 rho_O                              3.176373552e-22           1.029936604e-15
 rho_O2                             5.963111949e-19           2.413036512e-15
 rho_OH                             4.742855723e-21           5.863668883e-15
 rho_H2O                            2.710505431e-20            1.41918263e-15
 rho_HO2                            8.810253549e-23           1.630034612e-15
 rho_CH2                            2.946954525e-21           6.503107858e-13
 rho_CH2(S)                         1.148825916e-20           3.382887679e-11
 rho_CH3                            6.295377605e-21           4.216087336e-14
 rho_CH4                             1.76182853e-19           2.844014879e-15
 rho_CO                             1.127270753e-20           1.391184539e-15
 rho_CO2                             3.04931861e-20           1.523587015e-15
 rho_HCO                            8.389632915e-23           1.275775516e-14
 rho_CH2O                           1.852884572e-22           7.682801538e-16
 rho_CH3O                           1.488925103e-23           1.507017242e-15
 rho_C2H4                           2.382280164e-22            9.72912288e-16
 rho_C2H5                           1.488925103e-23           2.322798267e-15
 rho_C2H6                           2.117582368e-22           7.588684928e-16
 rho_N2                             1.084202172e-18            1.33284975e-15
 rho_AR                             2.698802673e-78           4.816307347e-16
 rho_omega_H2                       3.850210285e-15            8.63877345e-13
 rho_omega_H                         1.05355517e-14           5.260306269e-12
 rho_omega_O                        3.702713049e-15           4.750586737e-13
 rho_omega_O2                       8.626240849e-12           3.573251453e-11
 rho_omega_OH                       1.742975894e-13           1.109716055e-11
 rho_omega_H2O                      3.647652926e-13           2.533679801e-12
 rho_omega_HO2                      3.237810844e-15           2.690364345e-12
 rho_omega_CH2                      1.083008466e-13           2.982789969e-10
 rho_omega_CH2(S)                   4.221705044e-13           1.753557181e-08
 rho_omega_CH3                      2.313135412e-13           2.280059008e-11
 rho_omega_CH4                      1.610226334e-12           2.068272605e-11
 rho_omega_CO                       4.142629953e-13            3.92532273e-12
 rho_omega_CO2                      2.998510728e-13           2.607134106e-12
 rho_omega_HCO                      3.079095815e-15           5.832811253e-12
 rho_omega_CH2O                     2.846681224e-15           5.082414907e-13
 rho_omega_CH3O                     1.964574337e-16           9.492860097e-13
 rho_omega_C2H4                     3.385312863e-15           4.420378627e-13
 rho_omega_C2H5                      1.30676855e-16           2.564528798e-13
 rho_omega_C2H6                     3.715777686e-15            5.47067176e-13
 rho_omega_N2                       2.233417948e-11               1.496161611
 rho_omega_AR                       1.898208767e-71                         1
 rhoe_dot                             0.01115689753               1.439025256
 heatRelease                           0.1330910212           5.146579027e-12
 level = 1
 density                            1.301042607e-18           1.159081877e-15
 xmom                               2.780775412e-14           1.355460562e-11
 ymom                                2.63489026e-14           1.267822171e-11
 zmom                               3.579081476e-14           7.552181162e-13
 rho_E                              4.190951586e-09           1.082669107e-15
 rho_e                              4.190951586e-09            1.08266886e-15
 Temp                               2.955857781e-12           1.438172777e-15
 rho_H2                             8.470329473e-22           1.823256155e-15
 rho_H                              1.191140082e-22           2.848088435e-15
 rho_O                              7.940933881e-22           2.478971935e-15
 rho_O2                             4.878909776e-19           1.974376096e-15
 rho_OH                             1.588186776e-21           1.947179423e-15
 rho_H2O                            5.082197684e-20           2.636071292e-15
 rho_HO2                            1.852884572e-22           2.554666357e-15
 rho_CH2                            7.517266349e-22           8.480932895e-14
 rho_CH2(S)                         2.938788539e-21           4.443315513e-12
 rho_CH3                            1.614934437e-21           5.803914558e-15
 rho_CH4                            1.219727444e-19           1.969010996e-15
 rho_CO                             2.710505431e-20           2.930404822e-15
 rho_CO2                            4.065758147e-20            2.12499071e-15
 rho_HCO                            6.121136533e-23           4.814776459e-15
 rho_CH2O                           8.999725065e-22           3.072414777e-15
 rho_CH3O                            5.29395592e-23           2.849618172e-15
 rho_C2H4                           8.999725065e-22           2.644482844e-15
 rho_C2H5                           3.639594695e-23           2.933297106e-15
 rho_C2H6                           8.999725065e-22           1.998480818e-15
 rho_N2                              1.19262239e-18            1.46618974e-15
 rho_AR                             2.159042139e-78           3.604340291e-16
 rho_omega_H2                        1.21482685e-14           1.362666419e-12
 rho_omega_H                        1.477984402e-15           4.108825137e-13
 rho_omega_O                        1.057660903e-14           7.023542846e-13
 rho_omega_O2                       9.852948634e-12           2.365815427e-11
 rho_omega_OH                       2.463350704e-14           8.445633062e-13
 rho_omega_H2O                      7.488176745e-13           2.735254911e-12
 rho_omega_HO2                      3.035115562e-15           2.369249702e-12
 rho_omega_CH2                      4.311322739e-15           6.978433458e-12
 rho_omega_CH2(S)                   1.685441405e-14           3.757476499e-10
 rho_omega_CH3                      1.261664384e-14           5.899945112e-13
 rho_omega_CH4                      2.435084296e-12           1.608907007e-11
 rho_omega_CO                       3.614331057e-13           1.741052222e-12
 rho_omega_CO2                      6.295380883e-13            4.01464292e-12
 rho_omega_HCO                      4.805455079e-16           5.907964792e-13
 rho_omega_CH2O                     1.184122245e-14           1.053713287e-12
 rho_omega_CH3O                     6.836436799e-16           1.766761912e-12
 rho_omega_C2H4                     1.275195227e-14           8.305855264e-13
 rho_omega_C2H5                     4.063047641e-16           5.018130508e-13
 rho_omega_C2H6                     1.168683206e-14           8.757033805e-13
 rho_omega_N2                       2.744938391e-11                1.21149848
 rho_omega_AR                       2.530945026e-71                         1
 rhoe_dot                             0.02181926806               1.998571035
 heatRelease                            0.132619381           2.809035471e-12
```

**Comment by drummerdoc** [comment]
Looks great, but for that rhoedot diff:
`rhoe_dot                             0.02182471752                 1.9990798`
That one worries me a bit.  Any insights?

**Comment by hsitaram** [comment]
> Looks great, but for that rhoedot diff:
> `rhoe_dot 0.02182471752 1.9990798`
> That one worries me a bit. Any insights?

Rhoe_dot is not heat-release. It is the reaction source for total energy, which should be 0 ideally. The relative error is therefore high because it's estimated relative to something small.

**Comment by drummerdoc** [comment]
I guess rho.e / dt is very much larger than 1.e-2. I never have any gut feeling for e.

**Review by marchdf — APPROVED** [review]

**Pull request merged**
