### PR TITLE
Add JBBhack

### PR DESCRIPTION
**Pull request by marchdf**
I think it's time to merge this. It lets me run the sCO2 combustor with better mass fraction behavior. Can we find a better name?

### CODE REVIEW

**Comment by esclapez** [comment]
Sounds good. As for name:  `ode.OOB_guard` ?

**Comment by esclapez** [comment]
Or rather, `ode.init_oobGuard` since we're only doing that at the start of the integration.

**Comment by marchdf** [comment]
`ode.clean_init_massfrac` ?

**Review by esclapez — APPROVED** [review]
It looks good, thanks Marc. I'm fine with it being off by default.

**Pull request merged**
