### PR TITLE
Input of s3d ndodecane 35 species mechanism.

### PR DESCRIPTION
**Pull request by marient**
.

### CODE REVIEW

**Comment by esclapez** [comment]
Hello Marco,

I have generated the Fuego files corresponding to this mechanism. As you probably know, QSS mechanisms with Fortran routines need some by-hand plugin to make them work (that I don't know about but I guess you do) and of course, no GPU version available since the Fortran is not GPU-compliant.

**Comment by marient** [comment]
Hi Lucas,
Thank you very much!
Marco

From: Lucas Esclapez ***@***.***>
Reply-To: AMReX-Combustion/PelePhysics ***@***.***>
Date: Tuesday, March 16, 2021 at 10:19 AM
To: AMReX-Combustion/PelePhysics ***@***.***>
Cc: "Arienti, Marco" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [AMReX-Combustion/PelePhysics] Input of s3d ndodecane 35 species mechanism. (#148)


Hello Marco,

I have generated the Fuego files corresponding to this mechanism. As you probably know, QSS mechanisms with Fortran routines need some by-hand plugin to make them work (that I don't know about but I guess you do) and of course, no GPU version available since the Fortran is not GPU-compliant.

**Comment by esclapez** [comment]
Hi Marco,
If you've managed to get this mechanism working, maybe you can push your changes to this branch so that we can merge this PR and have the mechanism readily available in the development branch.

Lucas

**Comment by marient** [comment]
Thank you Lucas. Could you be so kind to remind me of the steps I need to take to merge? I don’t do it often and I don’t want to cause a disaster.
Cheers.
Marco

From: Lucas Esclapez ***@***.***>
Reply-To: AMReX-Combustion/PelePhysics ***@***.***>
Date: Wednesday, March 24, 2021 at 4:12 PM
To: AMReX-Combustion/PelePhysics ***@***.***>
Cc: "Arienti, Marco" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [AMReX-Combustion/PelePhysics] Input of s3d ndodecane 35 species mechanism. (#148)


Hi Marco,
If you've managed to get this mechanism working, maybe you can push your changes to this branch so that we can merge this PR and have the mechanism readily available in the development branch.

Lucas

**Comment by esclapez** [comment]
No worries!
At this point, all you have to do is commit your local changes to your local branch (`git add <anyNewFile>`, `git commit <anyNewFile> <anyModifiedFile>`) and push your branch up to github (`git push origin Marco/add_ndodecane_35`). I'll have a look at it and merge the PR, so you don't have to worry about it.

**Comment by marient** [comment]
Ok, done.

From: Lucas Esclapez ***@***.***>
Reply-To: AMReX-Combustion/PelePhysics ***@***.***>
Date: Wednesday, March 24, 2021 at 4:55 PM
To: AMReX-Combustion/PelePhysics ***@***.***>
Cc: "Arienti, Marco" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [AMReX-Combustion/PelePhysics] Input of s3d ndodecane 35 species mechanism. (#148)


No worries!
At this point, all you have to do is commit your local changes to your local branch (git add <anyNewFile>, git commit <anyNewFile> <anyModifiedFile>) and push your branch up to github (git push origin Marco/add_ndodecane_35). I'll have a look at it and merge the PR, so you don't have to worry about it.

**Comment by esclapez** [comment]
I have just added a Make.package to allow the Testing/Exec/ReactEval_C to compile with this mechanism, but I did not tested it further.
I'll merge this PR and feel free to open another one if it turns out something is not working properly.

**Comment by marient** [comment]
Cool, thanks!

From: Lucas Esclapez ***@***.***>
Reply-To: AMReX-Combustion/PelePhysics ***@***.***>
Date: Wednesday, March 24, 2021 at 5:25 PM
To: AMReX-Combustion/PelePhysics ***@***.***>
Cc: "Arienti, Marco" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [AMReX-Combustion/PelePhysics] Input of s3d ndodecane 35 species mechanism. (#148)


I have just added a Make.package to allow the Testing/Exec/ReactEval_C to compile with this mechanism, but I did not tested it further.
I'll merge this PR and feel free to open another one if it turns out something is not working properly.

**Pull request merged**
